In [2]:
import numpy as np

In [9]:
list = [20,27,9,12,31,17,4,50,39,35]
arr = np.array([list])

print(arr*4)

print(np.mean(arr))

print(np.median(arr))

print(np.std(arr))

i=np.argmin(arr)
print(arr.flat[i])

j=np.argmax(arr)
print(arr.flat[j])

mask = arr > 20 
print(arr[mask])

[[ 80 108  36  48 124  68  16 200 156 140]]
24.4
23.5
13.828955130450023
4
50
[27 31 50 39 35]


In [33]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
matrix = np.array(matrix)

print(np.shape(matrix))
#there are 3 rows and 4 columns

print(matrix[:,2])
print(matrix*2)

print(np.mean(matrix,axis=1)) #row mean
print(np.mean(matrix,axis=0)) #column mean 
print(np.mean(matrix))

print(np.max(matrix,axis=1))
print(np.min(matrix,axis=0))

flatten = matrix.flatten()
print(np.shape(flatten)) 
#1d array with 12 elements. it went from 2D to 1D
print(np.argmin(flatten))
print(np.argmax(flatten))
print(np.unravel_index(7,matrix.shape))
print(np.unravel_index(5,matrix.shape))

mask = matrix > 15 
print(matrix[mask])

print(np.sort(matrix,axis=1))




(3, 4)
[17 14 19]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[10.75 11.5  12.25]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
(12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [41]:


def mag_prime_num(arr):
    arr_new =[]
    for row in arr:
        for number in row:
            if number % 2 != 0:
                arr_new.append(row)
    return arr_new
    
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])
print(mag_prime_num(arr))                

[array([2, 3, 5]), array([2, 3, 5]), array([11, 13, 17]), array([11, 13, 17]), array([11, 13, 17]), array([ 7, 10, 13]), array([ 7, 10, 13])]


NameError: name 'is_prime' is not defined